[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.mysqli",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.curl",
  "php82Extensions.zip",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.opcache",
  "php82Packages.composer"
]

[phases.install]
cmds = ["if [ -d Login ]; then cd Login && composer install --no-dev --optimize-autoloader --no-interaction; fi"]

[start]
cmd = "PHP_CLI_SERVER_WORKERS=50 php -S 0.0.0.0:$PORT -d opcache.enable=1 -d opcache.enable_cli=1"
